{% set name = "neuralsens" %}
{% set version = "0.0.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 6eec63014ab50bd53f4b299dc7105fcbf76de68a99a66d55fc14297064d940f9


build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - poetry
  run:
    - python
    - numpy
    - pandas
    - matplotlib

test:
  imports:
    - neuralsens

about:
  home: "https://github.com/JaiPizGon/NeuralSens"
  license: "GNU General Public v3 or later (GPLv3+)"
  license_family: GPL3
  license_file: LICENSE
  summary: "Analysis functions to quantify inputs importance in neural network models."

extra:
  recipe-maintainers:
    - JaiPizGon
