[tool.poetry]
name = "neuralsens"
version = "0.0.4.dev9"
description = "Calculate word counts in a text file."
authors = ["Jaime Pizarroso Gonzalo", "Jose Portela Gonzalez", "Antonio Munoz San Roque"]
license = "GPU-3"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0",
            "setuptools>=42",
            "wheel",
            "numpy",
            "pandas",
            "scipy",
            "matplotlib"]
build-backend = "poetry.core.masonry.api"