{% set name = "neuralsens" %}
{% set version = "0.0.4.dev5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f7907a9ec1f6f7388ef0246ad418c03f905ea5696c779aec4413b8be6ba5de1a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - neuralsens

about:
  home: "https://github.com/JaiPizGon/NeuralSens"
  license: "GNU General Public v3 or later (GPLv3+)"
  license_family: GPL3
  license_file: LICENSE
  summary: "Analysis functions to quantify inputs importance in neural network models."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - JaiPizGon
